mjovanc/easyfood

EasyFood/app/src/main/res/layout/layout_eaterylist.xml

set margin to 15dp

---

EasyFood/app/src/main/AndroidManifest.xml
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMainActivity.java
EasyFood/app/src/main/res/layout/activity_main_manager.xml

Create manager main activity

---

EasyFood/app/build.gradle
EasyFood/app/google-services.json
EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/ICallback.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IEateriesCallback.java
EasyFood/app/src/main/java/com/example/easyfood/model/Eatery.java
EasyFood/app/src/main/java/com/example/easyfood/model/EateryAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/repository/EateryRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/customer/EateryActivity.java
EasyFood/build.gradle

Implementing Firebase to the project and adding methods for Eatery model.

Firebase test

---

EasyFood/app/src/main/java/com/example/easyfood/model/Order.java

Adding Order Model for holding order data.

---

EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/repository/EateryRepository.java

Fixing updating recyxclerview bug

Fixing view update bug

---

EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IProductsCallback.java
EasyFood/app/src/main/java/com/example/easyfood/model/Eatery.java
EasyFood/app/src/main/java/com/example/easyfood/model/Product.java
EasyFood/app/src/main/java/com/example/easyfood/repository/EateryRepository.java

Implementing getAllProducts(EateryID)

Firebase product

---

EasyFood/app/src/main/res/layout/activity_eatery.xml
EasyFood/app/src/main/res/layout/layout_eaterylist.xml

Changed the layout of the RecyclerView to CardView, added an ImageView with a dummy image for now.
Changes made in activity_eatery.xml and layout_eaterylist.xml.  Should be safe to merge.

Adding image to eatery adapter

---

EasyFood/app/src/main/java/com/example/easyfood/view/RegisterActivity.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/RegisterActivityViewModel.java
EasyFood/app/src/main/res/layout/activity_register.xml

Creating customer register form

---

EasyFood/app/src/main/java/com/example/easyfood/model/User.java
EasyFood/app/src/main/java/com/example/easyfood/repository/AuthRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/LoginActivity.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/LoginActivityViewModel.java
EasyFood/app/src/main/res/layout/activity_login.xml

Creating login form

---

EasyFood/app/src/main/AndroidManifest.xml
EasyFood/app/src/main/java/com/example/easyfood/model/User.java
EasyFood/app/src/main/java/com/example/easyfood/repository/AuthRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/BaseActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/LoginActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/MainActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/RegisterActivity.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/LoginActivityViewModel.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/RegisterActivityViewModel.java
EasyFood/app/src/main/res/layout/activity_login.xml
EasyFood/app/src/main/res/layout/activity_register.xml

Adding Authentication functionality

Merging auth functionality

---

EasyFood/app/src/main/res/layout/activity_eatery.xml
EasyFood/app/src/main/res/layout/activity_menu.xml

Fixing bugs in layouts where the recyclerview is ending outside the screen

Fixing layout bug in eatery activity

---

EasyFood/app/src/main/java/com/example/easyfood/view/LoginActivity.java
EasyFood/app/src/main/res/layout/activity_login.xml
EasyFood/app/src/main/res/layout/activity_register.xml

Adjusting some margins and naming

Adjusting auth layout

---

EasyFood/app/src/main/java/com/example/easyfood/view/MainActivity.java

Minor refactoring of MainActivity

---

EasyFood/app/src/main/AndroidManifest.xml
EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/model/Product.java
EasyFood/app/src/main/java/com/example/easyfood/repository/ManagerMenuRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMainActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/NewProductActivity.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/ManagerMenuViewModel.java
EasyFood/app/src/main/res/layout/activity_main_manager.xml
EasyFood/app/src/main/res/layout/activity_menu_manager.xml
EasyFood/app/src/main/res/layout/activity_product_new.xml
EasyFood/app/src/main/res/layout/layout_managermenulist.xml

Creating manager menu activity

---

EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/repository/ManagerMenuRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/NewProductActivity.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/ManagerMenuViewModel.java

It's now possible to remove product from Menu

Implementing remove product from menu

---

EasyFood/app/src/main/AndroidManifest.xml
EasyFood/app/src/main/java/com/example/easyfood/db/Firebase.java
EasyFood/app/src/main/java/com/example/easyfood/db/IDatabase.java
EasyFood/app/src/main/java/com/example/easyfood/repository/ManagerMenuRepository.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/EditProductActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/ManagerMenuAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/viewmodel/ManagerMenuViewModel.java
EasyFood/app/src/main/res/layout/activity_menu_manager.xml
EasyFood/app/src/main/res/layout/layout_managermenulist.xml

Adding edit product functionality

Implementing edit product from menu

---

EasyFood/app/src/main/java/com/example/easyfood/view/EateryAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/view/customer/EateryActivity.java
EasyFood/app/src/main/res/layout/activity_eatery.xml

Adding eatery search functionality

Implementing eatery search view

---

EasyFood/app/src/main/java/com/example/easyfood/view/ProductAdapter.java
EasyFood/app/src/main/java/com/example/easyfood/view/customer/ProductActivity.java
EasyFood/app/src/main/res/layout/activity_menu.xml

Adding functionality for Search Product in menu

Creating functionality for SearchView (Products)

---

EasyFood/app/src/main/java/com/example/easyfood/model/Order.java
EasyFood/app/src/main/java/com/example/easyfood/model/OrderStatusEnums.java
EasyFood/app/src/main/java/com/example/easyfood/model/ProductDocument.java
EasyFood/app/src/main/java/com/example/easyfood/repository/IOrdersCallback.java
EasyFood/app/src/main/java/com/example/easyfood/repository/IOrderssCallback.java
EasyFood/app/src/main/java/com/example/easyfood/repository/OrderRepository.java

Creating OrderRepository, adding getAllOrders() and senOrder()

Creating order repository

---

EasyFood/app/src/main/java/com/example/easyfood/view/manager/OrdersActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/OrdersAdapter.java
EasyFood/app/src/main/res/layout/activity_orders.xml
EasyFood/app/src/main/res/layout/layout_orderslist.xml

Creating OrdersActivity, OrdersAdapter with layouts

Creating orders activity

---

EasyFood/app/src/main/java/com/example/easyfood/model/Order.java
EasyFood/app/src/main/java/com/example/easyfood/model/Product.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/OrderActivity.java
EasyFood/app/src/main/java/com/example/easyfood/view/manager/OrdersActivity.java
EasyFood/app/src/main/res/layout/activity_order.xml

Creating order activity
